### ISSUE TITLE
yesterday's release to melodic breaks compilation

### ISSUE THREAD

**Issue by asherikov** [ros-industrial/ros_industrial_cmake_boilerplate#57]
I am getting multiple linking errors when building melodic on Ubuntu 18 with colcon, e.g.,
`undefined reference to `testing::ScopedTrace::~ScopedTrace()'` or `undefined reference to `testing::ScopedTrace::PushTrace(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'` in `tf2_geometry_msgs`.
Looks like a version conflict: `gtest.h` header provided by this package overrides default one, while the packages still link to the default gtest library built for each package individually:
```
$ grep -R PushTrace build/ | grep libgtest.so
Binary file build/reldebug/ros_industrial_cmake_boilerplate-googletest-build/googletest/libgtest.so matches
$ find ./build/ -iname "libgtest.so"
./build/reldebug/angles/gtest/googlemock/gtest/libgtest.so
./build/reldebug/tf2_geometry_msgs/gtest/googlemock/gtest/libgtest.so
./build/reldebug/libmavconn/gtest/googlemock/gtest/libgtest.so
...
```
gtest linking paths are configured somewhere in catkin guts, overriding them is a pain, and might need to be done for each package individually.

**Comment by gavanderhoorn** [comment]
Is this not #54?

**Comment by asherikov** [comment]
Yes, it is related. Pretty much it was fixed for 20/noetic and then released to 18/melodic, which obviously didnt work. Also this package has never been released in melodic, so what is the point of doing this now?

**Comment by gavanderhoorn** [comment]
Probably for https://github.com/ros/rosdistro/pull/31368.

There are still plenty of people using Melodic, so that would be one reason.

**Comment by gavanderhoorn** [comment]
As @Levi-Armstrong maintains this, we'll wait for him.

**Comment by asherikov** [comment]
Fixed by https://github.com/ros/rosdistro/pull/31403
