### ISSUE TITLE
extract_package_metadata doesn't handle semi colons

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial/ros_industrial_cmake_boilerplate#61]
This description in the package.xml
```
<description>test; test</description>
```

gives this error

```
CMake Error at /home/matthew/code/external/devel/lib/cmake/ros_industrial_cmake_boilerplate/extract_package_metadata.cmake:57 (string):
  string sub-command STRIP requires two arguments.
```

Removing the semi colon fixes it

**Comment by marip8** [comment]
Is this a solvable issue or just a limitation of the CMake commands? If it's just a limitation, then we should just document it on the README and close this issue
