### ISSUE TITLE
cpack macro does not generate correct name for windows

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_industrial_cmake_boilerplate#63]
It looks like the following lines need to be outside the if statement.
https://github.com/ros-industrial/ros_industrial_cmake_boilerplate/blob/77ca6b9d59bbe09f782077ce069de78902628e4a/ros_industrial_cmake_boilerplate/cmake/cmake_tools.cmake#L527-L531

**Comment by marip8** [comment]
Closing; addressed by #64
