### ISSUE TITLE
Cannot generate Debian packages

### ISSUE THREAD

**Issue by lanmo0923** [ros-industrial/ros_industrial_cmake_boilerplate#78]
I tried to use the method in the readme to generate the Debian package, but the third line does not work. Is it the generation method has  changed?
```
cd <workspace directory>
catkin build -DRICB_PACKAGE=ON
./src/ros_industrial_cmake_boilerplate/.run-cpack
```

**Comment by Levi-Armstrong** [comment]
Closing no response.
